name: 'Deploy to Firebase Cloud Functions'
author: 'edyrkaj <edyrkaj@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'green'
inputs:
  entrypoint:
    description: 'The entrypoint of the function'
    default: '.'
    required: false